spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: ateo1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
    protocol: stmp
server:
  port: 8080

#URLs
app:
  frontend:
    url: http://localhost:4200
  backend:
    url: http://localhost:8080
  cors:
    allowed-origins: ${app.frontend.url}

# kpay pour les paiements
kpay:
  api:
    url: https://admin.kpay.site/api/v1
    key: kpay_test_7fc55f857c129811f07eebc0619bb5ec26d22dfd4a22f198
    secret:
      key: 86cd716f493f27fce5fc2766c4dbff9a278bc8286f6e616d8be188437da1520c