spring:
  datasource:
    url: ${DATABASE_URL}
    username: ${DATABASE_USERNAME} 
    password: ${DATABASE_PASSWORD}
  jpa:
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
        temp: 
          use_jdbc_meatadata_defaults: false
  
  #mail:
   # host: smtp.gmail.com
   # port: 587
   # username: ${MAIL_USERNAME}
   # password: ${MAIL_PASSWORD}
   # properties:
    #  mail:
        # smtp:
        #   auth: true
        #   starttls:
        #     enable: true
  
 # redis:
  #  host: ${REDIS_HOST}
   # port: ${REDIS_PORT}

logging:
  level:
    com.ecommerce: WARN

server:
  port: 8080

#Informations de la BD sur supabase
DATABASE_URL: jdbc:postgresql://aws-1-eu-west-2.pooler.supabase.com:6543/postgres?user=postgres.oxprkgtttncqqznbcprd&password=7uq31LVG00YQHwoJ&sslmode=require
#DATABASE_USERNAME: postgres.oxprkgtttncqqznbcprd
#DATABASE_PASSWORD: 7uq31LVG00YQHwoJ

#URLs
app:
  frontend:
    url: https://e-commerce-f9c51.web.app
  backend:
    url: http://localhost:8080
  cors:
    allowed-origins: ${APP_COLORS_ALLOWED_ORIGINS}

#kpay pour les paiements
kpay:
  api:
    url: https://admin.kpay.site/api/v1
    key: kpay_test_3d5d8aae4f6122aefbfacb5c566485a2b1ff7ed6f344398e
    secret:
      key: 935c0db86cd86db65d1337b87210d450c36162a35d9670e90714751c53a1c2ec