spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/ecommerce
    username: postgres
    password: ateo1234
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.security.servlet.SecurityAutoConfiguration
  data:
    redis:
      host: localhost
      port: 6379
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false
    protocol: stmp
server:
  port: 8080

#URLs
app:
  frontend:
    url: http://localhost:4200
  backend:
    url: http://localhost:8080
  cors:
    allowed-origins: ${app.frontend.url}

# kpay pour les paiements
kpay:
  api:
    url: https://admin.kpay.site/api/v1
    key: kpay_test_3d5d8aae4f6122aefbfacb5c566485a2b1ff7ed6f344398e
    secret:
      key: 935c0db86cd86db65d1337b87210d450c36162a35d9670e90714751c53a1c2ec